# Aula 1 - An√°lise de Dados com Pandas

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/guilhermeonrails/data-jobs/refs/heads/main/salaries.csv")

In [3]:
df.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2025.0,SE,FT,Solutions Engineer,214000,USD,214000,US,100,US,M
1,2025.0,SE,FT,Solutions Engineer,136000,USD,136000,US,100,US,M
2,2025.0,MI,FT,Data Engineer,158800,USD,158800,AU,0,AU,M
3,2025.0,MI,FT,Data Engineer,139200,USD,139200,AU,0,AU,M
4,2025.0,EN,FT,Data Engineer,90000,USD,90000,US,0,US,M

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133349 entries, 0 to 133348
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   work_year           133339 non-null  float64
 1   experience_level    133349 non-null  object
 2   employment_type     133349 non-null  object
 3   job_title           133349 non-null  object
 4   salary              133349 non-null  int64
 5   salary_currency     133349 non-null  object
 6   salary_in_usd       133349 non-null  int64
 7   employee_residence  133349 non-null  object
 8   remote_ratio        133349 non-null  int64
 9   company_location    133349 non-null  object
 10  company_size        133349 non-null  object
dtypes: float64(1), int64(3), object(7)
memory usage: 11.2+ MB

In [5]:
df.describe()

           work_year        salary  salary_in_usd   remote_ratio
count  133339.000000  1.333490e+05  133349.000000  133349.000000
mean     2024.358770  1.632833e+05  157617.272098      20.905669
std         0.680627  2.173860e+05   74288.363097      40.590044
min      2020.000000  1.400000e+04   15000.000000       0.000000
25%      2024.000000  1.060200e+05  106000.000000       0.000000
50%      2024.000000  1.470000e+05  146206.000000       0.000000
75%      2025.000000  1.990000e+05  198000.000000       0.000000
max      2025.000000  3.040000e+07  800000.000000     100.000000

In [6]:
df.shape

(133349, 11)

In [7]:
linhas, colunas = df.shape[0], df.shape[1]
print('Linhas:', linhas)
print('Colunas:', colunas)

Linhas: 133349
Colunas: 11

In [8]:
df.columns

Index(['work_year', 'experience_level', 'employment_type', 'job_title',
       'salary', 'salary_currency', 'salary_in_usd', 'employee_residence',
       'remote_ratio', 'company_location', 'company_size'],
      dtype='object')

### Renomeando as colunas do DataFrame

In [9]:
# Dicion√°rio de renomea√ß√£o
novos_nomes = {
    'work_year': 'ano',
    'experience_level': 'senioridade',
    'employment_type': 'contrato',
    'job_title': 'cargo',
    'salary': 'salario',
    'salary_currency': 'moeda',
    'salary_in_usd': 'usd',
    'employee_residence': 'residencia',
    'remote_ratio': 'remoto',
    'company_location': 'empresa',
    'company_size': 'tamanho_empresa'
}

# Aplicando renomea√ß√£o
df.rename(columns=novos_nomes, inplace=True)

# Verificando resultado
df.head()

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,2025.0,SE,FT,Solutions Engineer,214000,USD,214000,US,100,US,M
1,2025.0,SE,FT,Solutions Engineer,136000,USD,136000,US,100,US,M
2,2025.0,MI,FT,Data Engineer,158800,USD,158800,AU,0,AU,M
3,2025.0,MI,FT,Data Engineer,139200,USD,139200,AU,0,AU,M
4,2025.0,EN,FT,Data Engineer,90000,USD,90000,US,0,US,M

### Analisando quais s√£os as categorias das colunas categ√≥ricas

#### N√≠vel de senioridade

In [10]:
# O m√©todo .value_counts() serve para contar quantas vezes cada valor √∫nico aparece em uma coluna.
df['senioridade'].value_counts()

senioridade
SE    77241
MI    40465
EN    12443
EX     3200
Name: count, dtype: int64

| Sigla | Significado | Descri√ß√£o                                 |
|-------|-------------|--------------------------------------------|
| SE    | Senior      | Profissional experiente (n√≠vel s√™nior)     |
| MI    | Mid         | N√≠vel intermedi√°rio                        |
| EN    | Entry       | Iniciante ou j√∫nior (entry-level)          |
| EX    | Executive   | Executivo, lideran√ßa s√™nior (C-Level)      |

#### Tipo de contrato

In [11]:
df['contrato'].value_counts()

contrato
FT    132563
CT       394
PT       376
FL        16
Name: count, dtype: int64

| Sigla | Significado  | Descri√ß√£o                                                           |
|-------|--------------|----------------------------------------------------------------------|
| FT    | Full-time    | Tempo integral ‚Äì trabalho padr√£o de 40h/semana ou per√≠odo completo   |
| PT    | Part-time    | Meio per√≠odo ‚Äì carga hor√°ria reduzida                                |
| CT    | Contract     | Contrato tempor√°rio ou por projeto ‚Äì geralmente por prazo determinado|
| FL    | Freelance    | Freelancer ‚Äì trabalho aut√¥nomo ou por demanda, sem v√≠nculo formal    |

#### Regime de trabalho

In [12]:
df['remoto'].value_counts()

remoto
0      105312
100     27718
50        319
Name: count, dtype: int64

O modelo remoto permite trabalhar de qualquer lugar sem precisar ir √† empresa. O modelo presencial exige ir at√© o escrit√≥rio todos os dias. O h√≠brido mistura os dois modelos. O modelo 'everywhere' √© mais raro e permite trabalhar de qualquer lugar do mundo sem restri√ß√£o de pa√≠s ou cidade.

| Sigla | Significado |
|-------|-------------|
| 0     | Presencial  |
| 100   | Remoto      |
| 50    | H√≠brido     |

#### Tamanho da empresa

In [13]:
df['tamanho_empresa'].value_counts()

tamanho_empresa
M    129561
L      3574
S       214
Name: count, dtype: int64

| Sigla | Significado  | Descri√ß√£o                                                           |
|-------|--------------|----------------------------------------------------------------------|
| M   | Medium    | Empresa de tamanho m√©dio|
| L    | Large    | Empresa de tamanho grande                                |
| S    | Small    | Empresa de tamanho pequeno|

### Modificando o nome das categorias:

In [14]:
senioridade = {
    'SE': 'senior',
    'MI': 'pleno',
    'EN': 'junior',
    'EX': 'executivo'
}
df['senioridade'] = df['senioridade'].replace(senioridade)
df['senioridade'].value_counts()

senioridade
senior       77241
pleno        40465
junior       12443
executivo     3200
Name: count, dtype: int64

In [15]:
contrato = {
    'FT': 'integral',
    'PT': 'parcial',
    'CT': 'contrato',
    'FL': 'freelancer'
}
df['contrato'] = df['contrato'].replace(contrato)
df['contrato'].value_counts()

contrato
integral      132563
contrato         394
parcial          376
freelancer        16
Name: count, dtype: int64

In [16]:
tamanho_empresa = {
    'L': 'grande',
    'S': 'pequena',
    'M':	'media'

}
df['tamanho_empresa'] = df['tamanho_empresa'].replace(tamanho_empresa)
df['tamanho_empresa'].value_counts()

tamanho_empresa
media      129561
grande       3574
pequena       214
Name: count, dtype: int64

In [17]:
mapa_trabalho = {
    0: 'presencial',
    100: 'remoto',
    50: 'hibrido'
}

df['remoto'] = df['remoto'].replace(mapa_trabalho)
df['remoto'].value_counts()

remoto
presencial    105312
remoto         27718
hibrido          319
Name: count, dtype: int64

In [18]:
df.head()

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,2025.0,senior,integral,Solutions Engineer,214000,USD,214000,US,remoto,US,media
1,2025.0,senior,integral,Solutions Engineer,136000,USD,136000,US,remoto,US,media
2,2025.0,pleno,integral,Data Engineer,158800,USD,158800,AU,presencial,AU,media
3,2025.0,pleno,integral,Data Engineer,139200,USD,139200,AU,presencial,AU,media
4,2025.0,junior,integral,Data Engineer,90000,USD,90000,US,presencial,US,media

Podemos tamb√©m resumir as informa√ß√µes categ√≥ricas com o m√©todo `describe()`, exibindo a quantidade de categorias √∫nicas, qual √© categoria mais frequente e sua respectiva frequ√™ncia:

In [19]:
df.describe(include='object')

,senioridade,contrato,cargo,moeda,residencia,remoto,empresa,tamanho_empresa
count,133349,133349,133349,133349,133349,133349,133349,133349
unique,4,4,390,26,102,3,95,3
top,senior,integral,Data Scientist,USD,US,presencial,US,media
freq,77241,132563,17314,126140,119579,105312,119641,129561

Com isso j√° conseguimos responder algumas perguntas, como:

* Qual o n√≠vel de experi√™ncia mais comum na base de dados?
* Qual √© o tipo de contrato mais frequente?
* Qual o cargo mais frequente na amostra?
* De qual pa√≠s s√£o a maioria dos profissionais da base?
* Qual √© o pa√≠s onde mais empresas da amostra est√£o sediadas?
* Qual o regime de trabalho mais comum?
* Qual √© o tamanho mais comum das empresas na amostra?

**O c√≥digo √© um passo a passo para entender, limpar e preparar a base de dados para an√°lises mais profundas, facilitando a visualiza√ß√£o de padr√µes e tend√™ncias no mercado de trabalho em ci√™ncia de dados.**

# Aula 2 - Prepara√ß√£o e limpeza dos Dados

O c√≥digo a seguir verifica a exist√™ncia de valores nulos (ausentes) em cada c√©lula do DataFrame df. O resultado √© um DataFrame booleano de mesma forma que o original, onde True indica a presen√ßa de um valor nulo e False indica a aus√™ncia.

In [20]:
df.isnull()

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
133344,False,False,False,False,False,False,False,False,False,False,False
133345,False,False,False,False,False,False,False,False,False,False,False
133346,False,False,False,False,False,False,False,False,False,False,False
133347,False,False,False,False,False,False,False,False,False,False,False
133348,False,False,False,False,False,False,False,False,False,False,False

Este comando exibe as primeiras 5 linhas do DataFrame df ap√≥s as opera√ß√µes de limpeza e prepara√ß√£o realizadas anteriormente. √â √∫til para verificar o estado atual do DataFrame.

In [21]:
df.head()

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,2025.0,senior,integral,Solutions Engineer,214000,USD,214000,US,remoto,US,media
1,2025.0,senior,integral,Solutions Engineer,136000,USD,136000,US,remoto,US,media
2,2025.0,pleno,integral,Data Engineer,158800,USD,158800,AU,presencial,AU,media
3,2025.0,pleno,integral,Data Engineer,139200,USD,139200,AU,presencial,AU,media
4,2025.0,junior,integral,Data Engineer,90000,USD,90000,US,presencial,US,media

Este c√≥digo calcula a quantidade de valores nulos em cada coluna do DataFrame df. O resultado √© uma s√©rie, onde o √≠ndice √© o nome da coluna e o valor √© a contagem de nulos naquela coluna. Isso nos mostra quais colunas t√™m dados faltando e em qual quantidade.

In [22]:
df.isnull().sum()

ano                10
senioridade         0
contrato            0
cargo               0
salario             0
moeda               0
usd                 0
residencia          0
remoto              0
empresa             0
tamanho_empresa     0
dtype: int64

Este c√≥digo retorna todos os valores √∫nicos presentes na coluna 'ano' do DataFrame df. Isso √© √∫til para entender a distribui√ß√£o dos anos na base de dados e identificar poss√≠veis inconsist√™ncias ou a presen√ßa de valores nulos (nan).

In [23]:
df["ano"].unique()

array([2025.,   nan, 2024., 2022., 2023., 2020., 2021.])

Este c√≥digo filtra o DataFrame df para exibir apenas as linhas que cont√™m pelo menos um valor nulo em qualquer coluna. O isnull() retorna um DataFrame booleano, any(axis=1) verifica se h√° algum True em cada linha (axis=1), e o resultado √© usado para indexar o DataFrame original. Isso ajuda a inspecionar as linhas que precisam de tratamento de valores ausentes.

In [24]:
df[df.isnull().any(axis=1)]

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
5588,NaN,senior,integral,Product Manager,184500,USD,184500,US,presencial,US,media
59692,NaN,pleno,integral,Engineer,110000,USD,110000,DE,presencial,DE,media
59710,NaN,junior,integral,Data Scientist,208800,USD,208800,US,presencial,US,media
59759,NaN,senior,integral,Software Engineer,135000,USD,135000,US,presencial,US,media
59789,NaN,senior,integral,Engineer,112000,USD,112000,US,presencial,US,media
131000,NaN,senior,integral,Machine Learning Engineer,163800,USD,163800,US,presencial,US,media
131006,NaN,senior,integral,Data Analytics Manager,204500,USD,204500,US,presencial,US,media
133054,NaN,junior,integral,Data Scientist,40000,USD,40000,JP,remoto,MY,grande
133281,NaN,pleno,integral,Machine Learning Engineer,180000,PLN,46597,PL,remoto,PL,grande
133317,NaN,pleno,integral,Data Scientist,130000,USD,130000,US,hibrido,US,grande

Este c√≥digo cria um DataFrame de exemplo chamado df_salarios com uma coluna 'nome' e uma coluna 'salario' contendo alguns valores nulos (np.nan). Em seguida, demonstra duas formas de preencher os valores nulos da coluna 'salario':

1. fillna(df_salarios['salario'].mean().round(2)): Preenche os valores nulos com a m√©dia da coluna 'salario', arredondada para duas casas decimais.

2. fillna(df_salarios['salario'].median()): Preenche os valores nulos com a mediana da coluna 'salario'. O resultado mostra o DataFrame original e as duas novas colunas com os valores nulos preenchidos.

In [29]:
import numpy as np

# Cria√ß√£o de um dataframe de teste para usar de exemplo
df_salarios = pd.DataFrame({
    'nome':["Eloise", "Enoque", "Carlos", "Victor","Edvaldo"],
    'salario':[4000, np.nan, 5000, np.nan, 100000]
})

# calcula a m√©dia salarial e substitui os nulos pela m√©dia e arredonda os valores
df_salarios['salario_media'] = df_salarios['salario'].fillna(df_salarios['salario'].mean().round(2))

# Calcula a mediana e substitui os nulos pela mediana
df_salarios['salario_mediana'] = df_salarios['salario'].fillna(df_salarios['salario'].median())

df_salarios

      nome   salario  salario_media  salario_mediana
0   Eloise    4000.0        4000.00           4000.0
1   Enoque       NaN       36333.33           5000.0
2   Carlos    5000.0        5000.00           5000.0
3   Victor       NaN       36333.33           5000.0
4  Edvaldo  100000.0      100000.00         100000.0

Este c√≥digo cria um DataFrame de exemplo chamado df_temperaturas com uma coluna 'Dia' e uma coluna 'Temperatura' contendo alguns valores nulos. Em seguida, demonstra o uso do m√©todo ffill() (forward fill) para preencher os valores nulos. O ffill() preenche os valores nulos com o √∫ltimo valor v√°lido anterior na mesma coluna. O resultado mostra o DataFrame original e a nova coluna com os valores nulos preenchidos usando o m√©todo ffill.

In [30]:
df_temperaturas = pd.DataFrame({
    'Dia':['Segunda', 'Ter√ßa', 'Quarta', 'Quinta', 'Sexta', 'S√°bado', 'Domingo'],
    'Temperatura':[30, np.nan, np.nan, 28, 27, 32, 36]
})

df_temperaturas['Preenchido_ffill'] = df_temperaturas['Temperatura'].ffill()

df_temperaturas

       Dia  Temperatura  Preenchido_ffill
0  Segunda         30.0              30.0
1    Ter√ßa          NaN              30.0
2   Quarta          NaN              30.0
3   Quinta         28.0              28.0
4    Sexta         27.0              27.0
5   S√°bado         32.0              32.0
6  Domingo         36.0              36.0

Este c√≥digo cria um DataFrame de exemplo chamado df_temperaturas com uma coluna 'Dia' e uma coluna 'Temperatura' contendo alguns valores nulos. Em seguida, demonstra o uso do m√©todo bfill() (backward fill) para preencher os valores nulos. O bfill() preenche os valores nulos com o pr√≥ximo valor v√°lido posterior na mesma coluna. O resultado mostra o DataFrame original e a nova coluna com os valores nulos preenchidos usando o m√©todo bfill.

In [31]:
df_temperaturas = pd.DataFrame({
    'Dia':['Segunda', 'Ter√ßa', 'Quarta', 'Quinta', 'Sexta', 'S√°bado', 'Domingo'],
    'Temperatura':[30, np.nan, np.nan, 28, 27, 32, 36]
})

df_temperaturas['Preenchido_bfill'] = df_temperaturas['Temperatura'].bfill()

df_temperaturas

       Dia  Temperatura  Preenchido_bfill
0  Segunda         30.0              30.0
1    Ter√ßa          NaN              28.0
2   Quarta          NaN              28.0
3   Quinta         28.0              28.0
4    Sexta         27.0              27.0
5   S√°bado         32.0              32.0
6  Domingo         36.0              36.0

Este c√≥digo cria um DataFrame de exemplo chamado df_cidades com uma coluna 'nome' e uma coluna 'Cidade' contendo alguns valores nulos. Em seguida, demonstra o uso do m√©todo fillna() para preencher os valores nulos com uma string espec√≠fica: 'N√£o informado'. O resultado mostra o DataFrame original e a nova coluna com os valores nulos preenchidos com a string.

In [35]:
df_cidades = pd.DataFrame({
    'nome':["Eloise", "Enoque", "Carlos", "Victor","Edvaldo"],
    'Cidade':['S√£o Paulo', np.nan, 'Bel√©m', np.nan, 'Rio Grande do Norte']

})

df_cidades['Cidade_preenchida'] = df_cidades['Cidade'].fillna('N√£o informado')
df_cidades

      nome               Cidade    Cidade_preenchida
0   Eloise            S√£o Paulo            S√£o Paulo
1   Enoque                  NaN        N√£o informado
2   Carlos                Bel√©m                Bel√©m
3   Victor                  NaN        N√£o informado
4  Edvaldo  Rio Grande do Norte  Rio Grande do Norte

Este c√≥digo cria um novo DataFrame chamado df_limpo removendo todas as linhas do DataFrame original df que cont√™m pelo menos um valor nulo. O m√©todo dropna() √© utilizado para realizar essa opera√ß√£o. O resultado √© um DataFrame sem valores ausentes.

In [36]:
df_limpo = df.dropna()

Este c√≥digo verifica a quantidade de valores nulos em cada coluna do novo DataFrame df_limpo. Ap√≥s a aplica√ß√£o do m√©todo dropna(), a contagem de valores nulos em todas as colunas deve ser zero, confirmando que as linhas com valores ausentes foram removidas.

In [37]:
df_limpo.isnull().sum()

ano                0
senioridade        0
contrato           0
cargo              0
salario            0
moeda              0
usd                0
residencia         0
remoto             0
empresa            0
tamanho_empresa    0
dtype: int64

Este comando exibe as primeiras 5 linhas do DataFrame df_limpo. √â √∫til para visualizar o DataFrame ap√≥s a remo√ß√£o das linhas com valores nulos.

In [38]:
df_limpo.head()

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,2025.0,senior,integral,Solutions Engineer,214000,USD,214000,US,remoto,US,media
1,2025.0,senior,integral,Solutions Engineer,136000,USD,136000,US,remoto,US,media
2,2025.0,pleno,integral,Data Engineer,158800,USD,158800,AU,presencial,AU,media
3,2025.0,pleno,integral,Data Engineer,139200,USD,139200,AU,presencial,AU,media
4,2025.0,junior,integral,Data Engineer,90000,USD,90000,US,presencial,US,media

Este comando exibe informa√ß√µes sobre o DataFrame df_limpo, incluindo o n√∫mero de linhas, o n√∫mero de colunas, o tipo de dado de cada coluna e a quantidade de valores n√£o nulos em cada coluna. Isso confirma que as linhas com valores nulos foram removidas e mostra os tipos de dados das colunas restantes.

In [40]:
df_limpo.info()

<class 'pandas.core.frame.DataFrame'>
Index: 133339 entries, 0 to 133348
Data columns (total 11 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   ano              133339 non-null  float64
 1   senioridade      133339 non-null  object
 2   contrato         133339 non-null  object
 3   cargo            133339 non-null  object
 4   salario          133339 non-null  int64
 5   moeda            133339 non-null  object
 6   usd              133339 non-null  int64
 7   residencia       133339 non-null  object
 8   remoto           133339 non-null  object
 9   empresa          133339 non-null  object
 10  tamanho_empresa  133339 non-null  object
dtypes: float64(1), int64(2), object(8)
memory usage: 12.2+ MB

Este c√≥digo converte o tipo de dado da coluna 'ano' no DataFrame df_limpo de ponto flutuante (float64) para inteiro de 64 bits (int64). O m√©todo assign() √© usado para criar uma nova coluna 'ano' com os valores convertidos, substituindo a coluna original.

In [41]:
df_limpo = df_limpo.assign(ano = df_limpo['ano'].astype('int64'))

Este comando exibe as primeiras 5 linhas do DataFrame df_limpo ap√≥s a convers√£o do tipo de dado da coluna 'ano'. √â √∫til para verificar se a convers√£o foi bem-sucedida e se a coluna 'ano' agora exibe valores inteiros.

In [42]:
df_limpo.head()

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,2025,senior,integral,Solutions Engineer,214000,USD,214000,US,remoto,US,media
1,2025,senior,integral,Solutions Engineer,136000,USD,136000,US,remoto,US,media
2,2025,pleno,integral,Data Engineer,158800,USD,158800,AU,presencial,AU,media
3,2025,pleno,integral,Data Engineer,139200,USD,139200,AU,presencial,AU,media
4,2025,junior,integral,Data Engineer,90000,USD,90000,US,presencial,US,media

Este comando exibe informa√ß√µes sobre o DataFrame df_limpo ap√≥s a convers√£o do tipo de dado da coluna 'ano'. Isso confirma que o tipo de dado da coluna 'ano' agora √© int64, como esperado.

In [43]:
df_limpo.info()

<class 'pandas.core.frame.DataFrame'>
Index: 133339 entries, 0 to 133348
Data columns (total 11 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   ano              133339 non-null  int64
 1   senioridade      133339 non-null  object
 2   contrato         133339 non-null  object
 3   cargo            133339 non-null  object
 4   salario          133339 non-null  int64
 5   moeda            133339 non-null  object
 6   usd              133339 non-null  int64
 7   residencia       133339 non-null  object
 8   remoto           133339 non-null  object
 9   empresa          133339 non-null  object
 10  tamanho_empresa  133339 non-null  object
dtypes: int64(3), object(8)
memory usage: 12.2+ MB

## Resumo da Aula 2 - Prepara√ß√£o e Limpeza dos Dados

Nesta aula, focamos na prepara√ß√£o e limpeza dos dados para garantir sua qualidade e usabilidade em an√°lises futuras.

1.  **Verifica√ß√£o de Valores Nulos:** Identificamos a presen√ßa de valores nulos no DataFrame utilizando `df.isnull()` e `df.isnull().sum()`. Verificamos que a coluna 'ano' possu√≠a 10 valores nulos.
2.  **Identifica√ß√£o dos Anos:** Verificamos os valores √∫nicos na coluna 'ano', confirmando a presen√ßa de `nan`.
3.  **Visualiza√ß√£o de Linhas com Nulos:** Filtramos e exibimos as linhas que continham valores nulos para inspecionar os dados ausentes.
4.  **Demonstra√ß√£o de M√©todos de Preenchimento:** Apresentamos diferentes m√©todos para tratar valores nulos em DataFrames de exemplo:
    *   Preenchimento com a m√©dia ou mediana (`fillna()`).
    *   Preenchimento com o √∫ltimo valor v√°lido anterior (`ffill()`).
    *   Preenchimento com o pr√≥ximo valor v√°lido posterior (`bfill()`).
    *   Preenchimento com um valor espec√≠fico ('N√£o informado').
5.  **Remo√ß√£o de Linhas com Nulos:** Criamos um novo DataFrame (`df_limpo`) removendo as linhas que continham valores nulos na coluna 'ano' utilizando `df.dropna()`.
6.  **Verifica√ß√£o da Limpeza:** Confirmamos que n√£o h√° mais valores nulos no `df_limpo` verificando `df_limpo.isnull().sum()`.
7.  **Verifica√ß√£o do DataFrame Limpo:** Visualizamos as primeiras linhas e as informa√ß√µes do `df_limpo` para confirmar a remo√ß√£o das linhas e os tipos de dados.
8.  **Convers√£o de Tipo de Dado:** Convertemos o tipo de dado da coluna 'ano' de float para inteiro (`int64`) no `df_limpo` para representar os anos de forma mais adequada.
9.  **Verifica√ß√£o da Convers√£o:** Visualizamos as primeiras linhas e as informa√ß√µes do `df_limpo` novamente para confirmar a convers√£o do tipo de dado da coluna 'ano'.

Com essas etapas, os dados foram limpos e preparados, removendo os valores ausentes na coluna 'ano' e ajustando seu tipo de dado para uma an√°lise mais consistente.